\--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM - FI
-- Project :      LANQ_S2.DM1
-- Author :       oswaldo121oswaldo@gmail.com
--
-- Date Created : Wednesday, June 21, 2023 17:31:37
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: DOCUMENTAL_F3_LANQ_S2 
--

CREATE TABLE DOCUMENTAL_F3_LANQ_S2(
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    TEMATICA       VARCHAR2(100)    NOT NULL,
    DURACION       NUMBER(5, 2)     NOT NULL,
    TRAILER        BLOB             NOT NULL,
    PAIS_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT DOCUMENTAL_F3_LANQ_S2_PK PRIMARY KEY (PROGRAMA_ID)
)
;



-- -- 
-- -- TABLE: HISTORICO_STATUS_PROGRAMA_LANQ_S2 
-- --

CREATE TABLE HISTORICO_STATUS_PROGRAMA_LANQ_S2(
    HISTORICO_STATUS_PROG_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                DATE             NOT NULL,
    PROGRAMA_ID                 NUMBER(10, 0)    NOT NULL,
    STATUS_PROGRAMA_ID          NUMBER(2, 0)     NOT NULL,
    CONSTRAINT HISTORICO_STATUS_PROGRAMA_LANQ_S2_PK PRIMARY KEY (HISTORICO_STATUS_PROG_ID)
)
;



-- -- 
-- -- TABLE: PAIS_R_LANQ_S2 
-- --

CREATE TABLE PAIS_R_LANQ_S2(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT PAIS_R_LANQ_S2 PRIMARY KEY (PAIS_ID)
)
;



-- -- 
-- -- TABLE: PELICULA_F3_LANQ_S2 
-- --

CREATE TABLE PELICULA_F3_LANQ_S2(
    PROGRAMA_ID                NUMBER(10, 0)    NOT NULL,
    PELICULA_ANTECEDENTE_ID    NUMBER(10, 0),
    DURACION                   NUMBER(5, 2)     NOT NULL,
    SINOPSIS                   VARCHAR2(500)    NOT NULL,
    CLASIFICACION              CHAR(1)          NOT NULL,
    CONSTRAINT PELICULA_F3_LANQ_S2_PK PRIMARY KEY (PROGRAMA_ID)
)
;



-- -- 
-- -- TABLE: PLAYLIST_F1_LANQ_S2 
-- --

CREATE TABLE PLAYLIST_F1_LANQ_S2(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION          NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PLAYLIST_F1_LANQ_S2_PK PRIMARY KEY (PLAYLIST_ID)
)
;



-- -- 
-- -- TABLE: PROGRAMA_F3_LANQ_S2 
--

CREATE TABLE PROGRAMA_F3_LANQ_S2(
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    FOLIO                 VARCHAR2(13)     NOT NULL,
    NOMBRE                VARCHAR2(100)    NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    FECHA_STATUS          DATE             NOT NULL,
    TIPO                  CHAR(1)          NOT NULL,
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PROGRAMA_F3_LANQ_S2_PK PRIMARY KEY (PROGRAMA_ID)
)
;



-- -- 
-- -- TABLE: SERIE_F3_LANQ_S2 
-- --

CREATE TABLE SERIE_F3_LANQ_S2(
    PROGRAMA_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CAPITULOS        NUMBER(3, 0)     NOT NULL,
    DURACION_CAPITULO    NUMBER(5, 2)     NOT NULL,
    TIPO_SERIE_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT SERIE_F3_LANQ_S2_PK PRIMARY KEY (PROGRAMA_ID)
)
;



-- -- 
-- -- TABLE: STATUS_PROGRAMA 
-- --

CREATE TABLE STATUS_PROGRAMA(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    CONSTRAINT STATUS_PROGRAMA_PK PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;



-- -- 
-- -- TABLE: TIPO_CUENTA_R_LANQ_S2 
-- --

CREATE TABLE TIPO_CUENTA_R_LANQ_S2(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT TIPO_CUENTA_R_LANQ_S2_PK PRIMARY KEY (TIPO_CUENTA_ID)
)
;



-- -- 
-- -- TABLE: TIPO_SERIE_R_LANQ_S2 
-- --

CREATE TABLE TIPO_SERIE_R_LANQ_S2(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERIE_R_LANQ_S2_PK PRIMARY KEY (TIPO_SERIE_ID)
)
;



-- -- 
-- -- TABLE: USUARIO_F2_LANQ_S2 
-- --

CREATE TABLE USUARIO_F2_LANQ_S2(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE             NOT NULL,
    FECHA_CUENTA_FIN    DATE             NOT NULL,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_F2_LANQ_S2 PRIMARY KEY (USUARIO_ID)
)
;



-- -- 
-- -- TABLE: DOCUMENTAL_F3_LANQ_S2 
-- --

ALTER TABLE DOCUMENTAL_F3_LANQ_S2 ADD CONSTRAINT PROGRAMA_F3_LANQ_S2_DOCUMENTAL_PROGRAMA_ID_FK 
    FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F3_LANQ_S2(PROGRAMA_ID)
;

ALTER TABLE DOCUMENTAL_F3_LANQ_S2 ADD CONSTRAINT PAIS_R_LANQ_S2_PAIS_ID_FK 
    FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS_R_LANQ_S2(PAIS_ID)
;


-- -- 
-- -- TABLE: HISTORICO_STATUS_PROGRAMA_LANQ_S2 
-- --

ALTER TABLE HISTORICO_STATUS_PROGRAMA_LANQ_S2 ADD CONSTRAINT STATUS_PROGRAMA_STATUS_PROGRAMA_ID_FK 
    FOREIGN KEY (STATUS_PROGRAMA_ID)
    REFERENCES STATUS_PROGRAMA(STATUS_PROGRAMA_ID)
;


-- 
-- TABLE: PELICULA_F3_LANQ_S2 
--

ALTER TABLE PELICULA_F3_LANQ_S2 ADD CONSTRAINT PROGRAMA_F3_LANQ_S2_PELICULA_PROGRAMA_ID_FK 
    FOREIGN KEY (PROGRAMA_ID)     
    REFERENCES PROGRAMA_F3_LANQ_S2(PROGRAMA_ID)
;


-- 
-- TABLE: PLAYLIST_F1_LANQ_S2 
--

ALTER TABLE PLAYLIST_F1_LANQ_S2 ADD CONSTRAINT USUARIO_F2_LANQ_S2_USUARIO_ID_FK 
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO_F2_LANQ_S2(USUARIO_ID)
;


-- 
-- TABLE: PROGRAMA_F3_LANQ_S2 
--

ALTER TABLE PROGRAMA_F3_LANQ_S2 ADD CONSTRAINT STATUS_PROGRAMA_PROGRAMA_STATUS_PROGRAMA_ID_FK
    FOREIGN KEY (STATUS_PROGRAMA_ID)
    REFERENCES STATUS_PROGRAMA(STATUS_PROGRAMA_ID)
;


-- 
-- TABLE: SERIE_F3_LANQ_S2 
--

ALTER TABLE SERIE_F3_LANQ_S2 ADD CONSTRAINT PROGRAMA_F3_LANQ_S2_SERIE_PROGRAMA_ID_FK
    FOREIGN KEY (PROGRAMA_ID)
    REFERENCES PROGRAMA_F3_LANQ_S2(PROGRAMA_ID)
;

ALTER TABLE SERIE_F3_LANQ_S2 ADD CONSTRAINT TIPO_SERIE_R_LANQ_S2_TIPO_SERIE_ID_FK
    FOREIGN KEY (TIPO_SERIE_ID)
    REFERENCES TIPO_SERIE_R_LANQ_S2(TIPO_SERIE_ID)
;


-- 
-- TABLE: USUARIO_F2_LANQ_S2 
--

ALTER TABLE USUARIO_F2_LANQ_S2 ADD CONSTRAINT TIPO_CUENTA_R_LANQ_S2_TIPO_CUENTA_ID_FK
    FOREIGN KEY (TIPO_CUENTA_ID)
    REFERENCES TIPO_CUENTA_R_LANQ_S2(TIPO_CUENTA_ID)
;
